services:
  app:
    extends:
      file: docker-compose.build.yml
      service: app
    environment:
      - STRATEGY=bands
      - CONFIG=./config/bands.json
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    command: ./run
